--- # Set firewall settings for servers
- hosts: scadamon
  become: yes
  strategy: debug 

  tasks:
  - name: Install UFW
    apt:
      name: ufw
      state: latest

  - name: Allow SSH in UFW
    ufw:
      rule: allow
      port: 22
      proto: tcp
      from_ip:  "{{ item }}"
    with_items:
      - 192.168.1.2 # For a single IP address
      - 192.168.2.0/24 # For a whole subnet
 
  - name: Allow all traffic between all servers in a group
    ufw:
      rule: allow
      from_ip: "{{ item }}"
    with_items:
      - 192.168.1.2
      - 192.168.1.3
      - 192.168.1.4
      - 192.168.1.5

  - name: Allow traffic out
    ufw:
      rule: allow
      direction: out

  - name: Default
    ufw:
      rule: deny
      direction: in

  - name: enable ufw
    ufw: 
      state: enabled
      logging: on

